apiVersion: v1
kind: Service
metadata:
  labels:
  {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
  {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
