apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testdeply
  name: testdeply
spec:
  replicas: 10
  selector:
    matchLabels:
      app: testdeply
  template:
    metadata:
      labels:
        app: testdeply
    spec:
      containers:
      - image: httpd:alpine3.18
        name: httpd
        command: ["/bin/bash", "-c"]
        args: ["sleep 5; exit 1"]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
